# Generated by Django 2.2 on 2021-04-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('Property_ID', models.IntegerField(default=0)),
                ('email_address', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
